let a = "Zubair";
console.log(a);
console.log(a[0]);
console.log(a[1]);
console.log(a[2]);
console.log(a[3]);
console.log(a[4]);
// console.log(a[6]);
console.log(a.length);
let real_name = "Zubair";
let friend = "Ateeq";
console.log("Hi I am " + real_name + " and his friends name is " + friend);
console.log(`Hi I am ${real_name} and his friends name is ${friend} `);
let b = "Asif";
console.log(b.toLowerCase());
// console.log(b.toUpperCase());
console.log(b.length);
console.log(b.slice(1, 3));
console.log(b.replace("As", "UZ"));
console.log(b.concat("uzair"));
